[package]
name = "mosaix-cli"
description = "Mosaix command-line client."
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mosaix"
path = "src/main.rs"

[dependencies]
mosaix-ipc = { path = "../mosaix-ipc" }
mosaix-persistence = { path = "../mosaix-persistence" }
clap = { workspace = true }
serde_json = { workspace = true }
