[package]
name = "mosaix-agent"
description = "Mosaix background window management agent."
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mosaix-agent"
path = "src/main.rs"

[dependencies]
mosaix-engine = { path = "../mosaix-engine" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(windows)'.dependencies]
mosaix-platform-windows = { path = "../mosaix-platform-windows" }
